services:
  bukhindor-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    container_name: bukhindor-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    # Добавляем healthcheck для проверки работоспособности
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 