name: bukhindor_web
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  
  # Navigation
  go_router: ^16.1.0
  
  # UI & Utils
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.1
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # HTTP & API
  dio: ^5.4.0
  dio_smart_retry: ^7.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  
  # Native Splash
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700 