name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: SSH key passphrase
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.KEY }}
        script: |
          whoami
          ls -al


